:PROPERTIES:
:ID:       880eb16e-3207-4f44-9b4c-ec8b41b9710f
:END:
#+title: Muhammad

Notes from the book "Muhammad: his life based on the earliest sources", by
Martin Lings.

* The House of God

** Ishmael and Isaac

#+BEGIN_QUOTE
As for Ishmael, I have heard thee. Behold, I have blessed him... and I will make
him a great nation. But My covenant will I establish with Isaac, which Sarah
shall bear unto thee at this set time in the next year.
#+END_QUOTE

#+BEGIN_QUOTE
As to Genesis, it is the book of Isaac and his descendants, not of Abraham's
other line. Of Ishmael it tells us: And God was with the lad; and he grew and
dwelt in the wilderness and became an archer.
#+END_QUOTE

** Sarah, Ishmael and the well of Zamzam

#+BEGIN_QUOTE
And God heard the voice of the lad; and the angel of God called to Hagar out
of heaven and said to her: What aileth thee, Hagar? Fear not, for God hath heard
the voice of the lad where he is. Arise and lift up the lad and hold him in thy
hand, for I will make him a great nation. And God opened her eyes, and she saw a
well of water.
#+END_QUOTE

** The origins of the Ka'bah

#+BEGIN_QUOTE
The Koran tells us that God showed him the exact site, near to the well of
Zamzam, upon which he (Abraham) and Ishmael must build a sanctuary; and they
were told how it must be built. Its name, Ka'bah, cube, is in virtue of its
shape which is approximately cubic; its four corners are towards the four points
of the compass. But the most holy object in that holy place is a celestial stone
which, it is said, was brought by an Angel to Abraham from the nearby hill Abu
Qubays, where it had been preserved ever since it had reached the earth. "It
descended from Paradise whiter than milk, but the sins of the sons of Adam made
it black." This black stone they built into the eastern corner of the Ka'bah;
and when the sanctuary was completed, God spoke again to Abraham and bade him
institute the rite of the Pilgrimage to Becca - or Mecca...
#+END_QUOTE

* A Great Loss

#+BEGIN_QUOTE
The descendants of Isaac also venerated the Ka'bah, as a temple that had been
raised by Abraham. (...). But as the centuries passed the purity of the worship
of the One God came to be contaminated. The descendants of Ishmael became too
numerous to live all in the valley of Mecca; and those who went to settle
elsewhere took with them stones from the holy precinct and performed rites in
honour of them. Later, through the influence of neighbouring pagan tribes, idols
came to be added to the stones; and finally pilgrims began to bring idols to
Mecca.
#+END_QUOTE

+ The jurhumites became lords over Mecca, eventually being driven out by the
  descendants of Ishmael. In their flee, they buried the Well of Zamzam, it's
  location forgotten ever since.
